language: objective-c
osx_image: xcode8.3
xcode_project: JSONFeed.xcodeproj
xcode_scheme: JSONFeed
xcode_sdk: iphonesimulator10.0
script: xcodebuild clean && xcodebuild build -project JSONFeed.xcodeproj -scheme JSONFeed -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.0' test | xcpretty --test --color
